### ISSUE TITLE
Compatibility issue and crashes

### ISSUE THREAD

**Issue by proactive-solutions** [seedante/CollectionViewAnimation#1]
Sample app is crashing and not compatible with new syntax of Swiff

**Comment by seedante** [comment]
crash clue?

**Comment by proactive-solutions** [comment]
Some issues with newer version of Swift. Which I have resolved
![screen shot 2016-07-21 at 1 06 41 pm](https://cloud.githubusercontent.com/assets/13619716/17014782/2364241a-4f44-11e6-9ead-8bd89b35ca2d.png)

If you press + or Delete button multiple times then app crashes. Getting bad acesss
![screen shot 2016-07-21 at 1 08 33 pm](https://cloud.githubusercontent.com/assets/13619716/17014830/5ff742ea-4f44-11e6-8e67-4f1ece63957f.png)

**Comment by seedante** [comment]
I can't reproduce + crash on my iPad mini(iOS 9.3), and reproduce delete crash with quickly tap delete button, the reason of latter is not same with your issue. Before delete animation finish, delete cell again make data source and view is not in sync and then crash.
